# Project information
site_name: The MondoRepo
site_url: https://abramjkline.github.io/mondomonorepo
site_author: Abe Kline
site_description: >-
  This project is a template for hosting projects and documentation.

# Repository
repo_name: abramjkline/mondomonorepo
repo_url: https://github.com/abramjkline/mondomonorepo

# Copyright
copyright: Copyright &copy; 2024 Abe Kline

# Configuration
theme:
  name: material
  palette:
    - scheme: slate
      primary: deep-orange
      accent: deep-orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
      colors:
        background: "#212121"
        foreground: "#B0BEC5"
        text: "#727272"
        selection-background: "#404040"
        accent-color: "#FF9800"
        green: "#c3e88d"
        yellow: "#ffcb6b"
        blue: "#82aaff"
        red: "#f07178"
        purple: "#c792ea"
        orange: "#f78c6c"
    - scheme: default
      primary: blue-grey
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
      colors:
        background: "#263238"
        foreground: "#B0BEC5"
        text: "#607D8B"
        selection-background: "#546E7A"
        selection-foreground: "#FFFFFF"
        accent-color: "#009688"
        green: "#c3e88d"
        yellow: "#ffcb6b"
        blue: "#82aaff"
        red: "#f07178"
        purple: "#c792ea"
        orange: "#f78c6c"
        cyan: "#89ddff"

  features:
 #   - navigation.tabs
 #   - navigation.expand
 #   - navigation.sections
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - toc.integrate
    - content.code.annotate
    - content.tabs.link
  icon:
    - admonition:
      note: fontawesome/solid/circle-info
      abstract: fontawesome/solid/circle-node
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/lightbulb
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull-crossbones
      bug: fontawesome/solid/robot
      example: octicons/code-16
      quote: fontawesome/solid/quote-left

extra_javascript:
  - https://unpkg.com/mermaid@8.14.0/dist/mermaid.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.3.0/tablesort.min.js

# Plugins
plugins:
  - monorepo
  - search
  - awesome-pages
  - glightbox:
      touchNavigation: True
      loop: False
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: True
      draggable: True
      auto_caption: False
      caption_position: bottom

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/abramjkline
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/abekline
  generator: false

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.tabbed:
      alternate_style: True
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.highlight

# Navigation
nav:
  - Home: index.md
  - Coding: 
    - Home: ./coding/index.md
    - Utilities:
      - GitHub Pages: ./coding/github-pages.md
      - Playwright: ./coding/playwright.md
      - GitHub Actions: ./coding/github-actions.md
    - Projects:
      - COVID-19 (SAS): ./coding/covid-19.md
  
  - Songwriting:
    - Home: ./songwriting/index.md
    - Recordings:
      - List of Recordings: ./songwriting/recordings.md
    - Lyrics:
      - Eleven: ./songwriting/11.md
 